---
title: "Analysis of Specific & Demographic info for PhD"
output: html_notebook
---



```{r echo=FALSE}
source('scripts/Required.R')

downloadOSFdata()
loadalldata()
Demos<-read.csv("data/All_demographics.csv", header = TRUE)
fixnocursorcolnames()
loadcolors()
```

```{r, echo = FALSE}
### Create Data to use for ANOVA's and t-tests

ANOVAdata<- PrepdataforANOVA1(active_reaches, passive_reaches, pause_reaches[33:320,], nocursor_reaches[33:320,],nocursorI_reaches[33:320,], terminal_reaches )
ANOVAPdata<- PrepdataforPropANOVA(active_localization,passive_localization, terminal_localization, exposure_localization, nocursor_nocursors, nocursorI_nocursors)


TtestPdata<- PrepdataforPropT(active_localization, passive_localization,nocursor_nocursors, nocursorI_nocursors, terminal_localization,exposure_localization)
Ttestdata<- PrepdataforT(active_reaches, passive_reaches, pause_reaches[33:320,], nocursor_reaches[33:320,], nocursorI_reaches[33:320,], terminal_reaches)
```


```{r, echo = FALSE}
#Comparing Males and Females within Each Experiment (localization and no-cursor trials)
IndependentT(TtestPdata, "Passive")
IndependentT(TtestPdata, "Active")
IndependentT(TtestPdata, "Terminal")# there is a difference @ end of 1st rotation
IndependentT(TtestPdata, "Exposure")
IndependentT(TtestPdata, "No-Cursor")# difference @ beginning of both rotations
IndependentT(TtestPdata, "No-CursorI")# different @ end of 1st rotation
Overallttestofsex(TtestPdata)# when i compare overall, there is a difference between males and females @ the end of 1st rotation. Wrong because it includes no-cursors and localizations 


#Comparing Males and Females within Each Experiment (Reach Trials)
IndependentT(Ttestdata, "Passive")# difference @ beginning of 2nd rotation
IndependentT(Ttestdata, "Active") # different @ end of 2nd rotation & error clamp
IndependentT(Ttestdata, "Terminal")
IndependentT(Ttestdata, "Pause")
IndependentT(Ttestdata, "No-Cursor")# difference @ beginning of 2nd rotation
IndependentT(Ttestdata, "No-CursorI")
Overallttestofsex(Ttestdata)# when i compare overall, there is no difference between males and females 


#Experiment 1 Reaches Males vs female
Sexcomparisonexp1(Ttestdata) # significant difference @ end of 1st rotation and 2nd rotation

#Experiment 1 Implicit Measures male vs female
Sexcomparisonexp1REA(TtestPdata) # no difference anywhere 
Sexcomparisonexp1prop(TtestPdata) # no difference

#Experiment 2 Reaches male vs female
Sexcomparisonexp2Reach(Ttestdata)# significant @ 2nd rotation 15 males out of 64 subjects
exposuresexcomparison() #No difference between beginning or end of error clamp trials. 

#Experiment 2 Localizations male vs female
Sexcomparisonexp2prop(TtestPdata) # significant @ end of 1st Rotation 22 males out of 96 people 

#Experiment 3 Variation reaches and localizations
V_RM<-VariationTcombine(variation_reaches) # there is no difference between males and females during aligned training. 
V_RM<-VariationTcombine(variation_localization) # there is no difference between males and females during aligned training. 

```